export const data = [
  {
    id: 1,
    name: "Password generator app",
    img: "./images/projects/Password-generator-app.jpeg",
    live: "https://key-master.netlify.app/",
    link: "https://github.com/ibrahim11elian/password-generator",
    category: "front",
  },
  {
    id: 2,
    name: "where in the world countries",
    img: "./images/projects/where-in-world.jpg",
    live: "https://where-in-the-world-countries.netlify.app/",
    link: "https://github.com/ibrahim11elian/where-in-the-world",
    category: "front",
  },
  {
    id: 3,
    name: "Storefront Backend",
    link: "https://github.com/ibrahim11elian/store-front",
    category: "back",
  },
  {
    id: 4,
    name: "Weather-Journal App",
    img: "./images/projects/weather.png",
    live: "https://weather-by-zip-code.herokuapp.com/",
    link: "https://github.com/ibrahim11elian/weather-app-py-zip-code",
    category: "full",
  },
  {
    id: 5,
    name: "Shortly URL shortening API",
    img: "./images/projects/shortly.jpg",
    live: "https://shortly-for-url.netlify.app/",
    link: "https://github.com/ibrahim11elian/url-shortening",
    category: "front",
  },
  {
    id: 6,
    name: "My Todo",
    img: "./images/projects/todo.jpg",
    live: "https://my-todo-real.netlify.app/",
    link: "https://github.com/ibrahim11elian/My-Todo",
    category: "front",
  },
  {
    id: 7,
    name: "Yellow Moon",
    img: "./images/projects/yellow.png",
    live: "https://ibrahim11elian.github.io/yellow-moon/",
    link: "https://github.com/ibrahim11elian/yellow-moon",
    category: "front",
  },
  {
    id: 8,
    name: "Image-Processing-API",
    link: "https://github.com/ibrahim11elian/Image-Processing-API",
    category: "back",
  },
  {
    id: 9,
    name: "Advice generator app",
    img: "./images/projects/advice.jpg",
    live: "https://ibrahim11elian.github.io/advice-generator-app/",
    link: "https://github.com/ibrahim11elian/advice-generator-app",
    category: "front",
  },
  {
    id: 10,
    name: "Online Education - landing page",
    img: "./images/projects/education.png",
    live: "https://online-education-landing-page.netlify.app/",
    link: "https://github.com/ibrahim11elian/online-education-landing-page",
    category: "front",
  },
  {
    id: 11,
    name: "E-commerce product page",
    img: "./images/projects/e-commerce.jpg",
    live: "https://ibrahim11elian.github.io/E-commerce-product-page/",
    link: "https://github.com/ibrahim11elian/E-commerce-product-page",
    category: "front",
  },
];
